import Head from "next/head";
<<<<<<< HEAD
import Header from "@/components/navigation/header/header";
=======

import SliderCard from "@/components/cards/slider-card/slider-card";
import DestinationCard from "@/components/cards/destination-card/destination-card";
import Navbar from "@/components/navbar/navbar";
import HeadingOne from "@/components/typography/headings/headingOne";
>>>>>>> typography

export default function Home() {
  return (
    <>
      <Header />;
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
<<<<<<< HEAD
        <h1>Saga</h1>
=======
        <>
          {/* <h1>Saga</h1> */}
          <HeadingOne mainHeading>Saga Asia</HeadingOne>
          <DestinationCard />
          <SliderCard />
        </>
>>>>>>> typography
      </main>
    </>
  );
}
